---
title: "Coronavirus Covid-19"
date: "`r paste0('update:', format(Sys.time(), '%d %B, %Y'))`"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: yeti
    #navbar:
    #  - { title: "Blog", href: "https://dsqiansun.github.io/blog/", align: right }
---

```{r setup, include=FALSE}
pacman::p_load(knitr,flexdashboard, readr, fs, tidyverse, leaflet, plotly, DT, htmltools, forecast, data.table)

confirmed_path = 'COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
deceased_path = 'COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv'
data_confirmed  <-  read_csv(confirmed_path)
data_deceased  <-  read_csv(deceased_path)
# Get latest data
current_date <- as.Date(names(data_confirmed)[ncol(data_confirmed)], format = "%m/%d/%y")
changed_date <- file_info('COVID-19/')$change_time

# Get evolution data by country
data_confirmed_sub <- data_confirmed %>%
  pivot_longer(names_to = "date", cols = 5:ncol(data_confirmed)) %>%
  group_by(`Province/State`, `Country/Region`, date, Lat, Long) %>%
  summarise("confirmed" = sum(value, na.rm = T))

# data_recovered_sub <- data_recovered %>%
#   pivot_longer(names_to = "date", cols = 5:ncol(data_recovered)) %>%
#   group_by(`Province/State`, `Country/Region`, date, Lat, Long) %>%
#   summarise("recovered" = sum(value, na.rm = T))

data_deceased_sub <- data_deceased %>%
  pivot_longer(names_to = "date", cols = 5:ncol(data_deceased)) %>%
  group_by(`Province/State`, `Country/Region`, date, Lat, Long) %>%
  summarise("deceased" = sum(value, na.rm = T))


data_evolution <- data_confirmed_sub %>%
  full_join(data_deceased_sub) %>%
  ungroup() %>%
  mutate(date = as.Date(date, "%m/%d/%y")) %>%
  arrange(date) %>%
  group_by(`Province/State`, `Country/Region`, Lat, Long) %>%
  mutate(
    recovered = lag(confirmed, 14, default = 0) - deceased,
    recovered = ifelse(recovered > 0, recovered, 0),
    active = confirmed - recovered - deceased
  ) %>%
  pivot_longer(names_to = "var", cols = c(confirmed, recovered, deceased, active)) %>%
  ungroup()

# Calculating new cases
data_evolution <- data_evolution %>%
  group_by(`Province/State`, `Country/Region`) %>%
  mutate(value_new = value - lag(value, 4, default = 0)) %>%
  ungroup()


data_atDate <- function(inputDate) {
  data_evolution[which(data_evolution$date == inputDate),] %>%
    distinct() %>%
    pivot_wider(id_cols = c("Province/State", "Country/Region", "date", "Lat", "Long"), names_from = var, values_from = value) %>%
    filter(confirmed > 0 |
             recovered > 0 |
             deceased > 0 |
             active > 0)
}


top5_countries <- data_evolution %>%
  filter(var == "active", date == current_date) %>%
  group_by(`Country/Region`) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  arrange(desc(value)) %>%
  top_n(5) %>%
  select(`Country/Region`) %>%
  pull()


addLabel <- function(data) {
  data$label <- paste0(
    '<b>', ifelse(is.na(data$`Province/State`), data$`Country/Region`, data$`Province/State`), '</b><br>
    <table style="width:120px;">
    <tr><td>Confirmed:</td><td align="right">', data$confirmed, '</td></tr>
    <tr><td>Deceased:</td><td align="right">', data$deceased, '</td></tr>
    <tr><td>Estimated Recoveries:</td><td align="right">', data$recovered, '</td></tr>
    <tr><td>Active:</td><td align="right">', data$active, '</td></tr>
    </table>'
  )
  data$label <- lapply(data$label, HTML)

  return(data)
}
data <- data_atDate(max(data_evolution$date))%>% addLabel()


```

Visualisation
=======================================================================

Row
-----------------------------------------------------------------------

### Confirmed {.value-box}

```{r}
valueBox(format(sum(data$confirmed, na.rm = T), big.mark=","))

```

### Recovered {.value-box}

```{r}

valueBox(format(sum(data$recovered, na.rm = T), big.mark=","))
```

### Deceased {.value-box}

```{r}
valueBox(format(sum(data$deceased, na.rm = T), big.mark=","))

```

### Active {.value-box}

```{r}
valueBox(format(sum(data$active, na.rm = T), big.mark=","))
```





Row
-----------------------------------------------------------------------

### Global visualisation {data-width=600}

```{r}
zoomLevel=2
leaflet(data = data) %>%
    addTiles() %>%
    addCircleMarkers(
      lng          = ~Long,
      lat          = ~Lat,
      radius       = ~log(confirmed^(zoomLevel / 2)),
      stroke       = FALSE,
      fillOpacity  = 0.5,
      popup = ~label,
      label  = ~label,
      #labelOptions = labelOptions(textsize = 15),
      group        = "Confirmed"
    ) %>%
  #  addCircleMarkers(
  #    lng          = ~Long,
  #    lat          = ~Lat,
  #    radius       = ~log(confirmedPerCapita^(zoomLevel)),
  #    stroke       = FALSE,
  #    color        = "#00b3ff",
  #    fillOpacity  = 0.5,
     # label        = ~label,
      #labelOptions = labelOptions(textsize = 15),
 #     group        = "Confirmed (per capita)"
#    ) %>%
    addCircleMarkers(
      lng          = ~Long,
      lat          = ~Lat,
      radius       = ~log(recovered^(zoomLevel)),
      stroke       = FALSE,
      color        = "#005900",
      fillOpacity  = 0.5,
      popup = ~label,
      label        = ~label,
      #labelOptions = labelOptions(textsize = 15),
      group = "Estimated Recoveries"
    ) %>%
    addCircleMarkers(
      lng          = ~Long,
      lat          = ~Lat,
      radius       = ~log(deceased^(zoomLevel)),
      stroke       = FALSE,
      color        = "#E7590B",
      fillOpacity  = 0.5,
      popup = ~label,
      label        = ~label,
      #labelOptions = labelOptions(textsize = 15),
      group        = "Deceased"
    ) %>%
    addCircleMarkers(
      lng          = ~Long,
      lat          = ~Lat,
      radius       = ~log(active^(zoomLevel / 2)),
      stroke       = FALSE,
      color        = "#f49e19",
      fillOpacity  = 0.5,
      popup = ~label,
      label        = ~label,
      #labelOptions = labelOptions(textsize = 15),
      group        = "Active"
)
          # ) %>%
    # addCircleMarkers(
    #   lng          = ~Long,
    #   lat          = ~Lat,
    #   radius       = ~log(activePerCapita^(zoomLevel)),
    #   stroke       = FALSE,
    #   color        = "#f4d519",
    #   fillOpacity  = 0.5,
    #   #label        = ~label,
    #   #labelOptions = labelOptions(textsize = 15),
    #   group        = "Active (per capita)"
    # )
```


### Top country {data-width=400}

```{r}
data_per_country = as.data.table(data[,c('Country/Region', 'confirmed', 'deceased' )])[, lapply(.SD,sum), by=.(`Country/Region`)]

data_per_country$'death rate(%)' = round(data_per_country$deceased/data_per_country$confirmed*100, 2)
DT::datatable(data_per_country[order(-confirmed)],
              rownames = FALSE,
              options = list(
              pageLength = 13
  ))


```


Data
===================================== 

Column {.tabset}
-------------------------------------
   
### Data by Country
```{r}
data_per_country = as.data.table(data[,c('Country/Region', 'confirmed','recovered', 'deceased', 'active' )])[, lapply(.SD,sum), by=.(`Country/Region`)]

data_per_country$'death rate(%)' = round(data_per_country$deceased/data_per_country$confirmed*100, 2)
DT::datatable(data_per_country[order(-confirmed)],
              rownames = FALSE,
              filter = 'top',
              extensions = 'Buttons',
              options = list(
              dom = 'Bfrtip',
              buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
              pageLength = 13
  ))

```


### Data by Province
```{r}
data$'death rate(%)' = round(data$deceased/data$confirmed*100, 2)

DT::datatable(data[,c("Province/State", "Country/Region",  "confirmed","recovered",  "deceased",  "active",'death rate(%)')],
              rownames = FALSE,
              filter = 'top',
              extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
    pageLength = 13
  ))

```


Motivation
===================================== 
